package recommender

import "testing"

type post struct {
	title string
	body  string
}

var posts = []post{
	post{
		title: "The theory of visitors",
		body: `I went on a Tinder date with a schoolteacher who read me poetry aloud on his faded leather couch, but he seemed a little too earnest for me, so I went on a Hinge date with a musician who sang songs to me from the piano, but I was afraid to get involved with another creative type, and then I went on a Raya date with a movie producer who took me to a dinner so fancy it felt like a brag, and I imagined what it would be like to be a stepfather to his daughters, flaxen-haired sprites with names like Annabelle or Clarissa, but then I decided I was too young for all that, and I went on a date with a college student I met on Bumble who told me he couldn’t afford to eat out, so we sat on a curb on Sunset eating soft corn tacos from a truck on the corner, and for a moment I felt older than I really was, older than I had ever been before, though in fact I wasn’t even 30 yet. I went on dates with older guys and learned to get their references, the same allusions to movies and television shows released before I was born that seemed to be touchstones for gay men of a certain age — of course I love Beaches! — but I also went on dates with guys my own age or even younger, and I was comfortable with their language, too, Snapchatting selfies from my bed captioned “tired af” dotted with sleepy-eyed emojis. When I went on dates with successful guys, I knew what to say, commiserating over how crowded Soho House had become (it’s overrun!), but later I would complain to friends about their uninterrogated privilege and the high likelihood that they had secret cocaine habits, because rich guys so often do. When I went on dates with guys who were broke, I related to them, too, that needling anxiety of feeling like you never have enough in a city where everyone seems to have so much, but I would rule them out — telling friends that I needed someone more “worldly” and “accomplished,” this politely coded classism that still allowed me to feel good about myself.
		I went on dates in cities all over the country, wherever I was, even if I was only there for a night or two, finding some guy on an app who might keep me company over dinner or drinks. I went on dates when I was happy, and I went on dates when I was sad. I went on dates to feel complete when I felt empty, and when I felt complete on my own I went on dates then, too, because surely, I thought, I should want to be in a partnership composed of two whole people. These motivations were equally powerful — both the allure of fullness when I was starving and the allure of a complement to something that was already just fine on its own, the way a nice wine might pair with a good meal. I went on dates even when I didn’t want to, when I would have preferred to stay home and watch Netflix or go out with my friends, because if I did not go on dates I might never find love, and I knew that love was the highest calling.
		Never mind that I wasn’t even sure whether I was capable of falling in love again, at least with anyone who would love me back. My partner, a man I thought I would marry, left me unexpectedly, and I ended up fleeing New York for Los Angeles, though I still went back to New York sometimes for work and there I went on dates too. I didn’t want to be alone in my new life, free as I was from the shackles of a long-term relationship. I heard people say sometimes that they weren’t dating so they could focus on themselves, and I always found this curious, maybe because my identity as a single man was so slippery. I saw myself with the sharpest focus through the prism of a date, certainly more than I ever did when I was alone, puttering around my apartment or walking to work. On a date, my roughest qualities shifted into relief as I put my best face forward, highlighting only my most appealing features. There, I could be relaxed, dynamic, charismatic, prone to digressions of affectionate self-deprecation that I thought were charming — I hoped they were, at least. Alone, I was anxious. My internal monologue circled a nucleus of self-loathing, recursive and redundant, like a planet orbiting a sun. I never liked myself more than when I was with a guy who liked me.
		But after the date ended, whether with a friendly hug or a lingering kiss or even sex, whatever it was, the moment I was alone again, loneliness would roll in like New England fog. I felt profoundly sad. I had gotten sober years earlier, when I was still a teenager, so I couldn’t medicate the feelings away with wine or pills. Sometimes I would pick up junk food and overeat, looking for satiety that the night had failed to give me, but that bad habit outgrew its usefulness too. Mostly I called old friends to tell them how well things were going or sat alone on my roof, looking out at the city and trying to will the feelings away, swiping endlessly on dating apps and making conversation with strangers.
		One night, not long after I moved to Los Angeles, after having dinner with a handsome but dull young man I’d met on Tinder, I drove up into the hills to my friend Debby’s house. It was the sort of balmy summer night that California did so well, with the smog settling heavy over the Santa Monica Mountains. Once there, I collapsed into a chair on her porch.
		“I’m so sick of going on dates,” I said.
		“Then why do you keep doing it?” Debby asked.
		“Because if I do it enough, then eventually I won’t have to do it anymore,” I said. “But I can’t seem to get anyone to stick around.” I hesitated. “Or maybe I’m the one who never sticks around. Sometimes it’s hard to tell.”
		She leaned in. “Do you believe in the theory of visitors?” She said this conspiratorially, as if she was sharing with me a secret.
		“What’s that?” I asked.`,
	},
}

func TestGetWords(t *testing.T) {
	getWords(posts[0].body)
}
